### ISSUE TITLE
Error updating Project Settings -> Kanbine

### ISSUE THREAD

**Issue by david-drummond** [JavaNut13/kanbine#6]
undefined method `[]' for nil:NilClass

Error occurs at:
plugins/kanbine/app/controllers/kanbine/settings_controller.rb:8:in `settings'

Note, I do not have tags plugin installed.

**Comment by JavaNut13** [comment]
Also fixed at some point yesterday afternoon. Problem was that part of the form doesn't exist if there is no tags plugin installed, so part of `params` is nil.
